feat: button-component
yamada-ui/yamada-components pull request #243
Opened 2024-06-20 13:53 UTC by taku10101

Closes #75 

## Description

add Primary Buttons

## Current behavior (updates)

## New behavior

## Is this a breaking change (Yes/No):

## Additional Information

2024-06-20 15:40 UTC, cidkumagai requested changes

2024-06-20 15:40 UTC, cidkumagai commented on package.json
> +  "packageManager": "pnpm@9.1.3+sha512.7c2ea089e1a6af306409c4fc8c4f0897bdac32b772016196c469d9428f1fe2d5a21daf8ad6512762654ac645b5d9136bb210ec9a00afa8dbc4677843ba362ecd"
Why is this change necessary?

2024-06-21 00:42 UTC, taku10101 commented on package.json
> +  "packageManager": "pnpm@9.1.3+sha512.7c2ea089e1a6af306409c4fc8c4f0897bdac32b772016196c469d9428f1fe2d5a21daf8ad6512762654ac645b5d9136bb210ec9a00afa8dbc4677843ba362ecd"
sorry I`m missing

2024-06-21 01:59 UTC, kurakke approved these changes

2024-06-21 02:26 UTC, cidkumagai approved these changes

2024-06-21 02:27 UTC, cidkumagai commented
LGTM!

2024-06-21 10:45 UTC, merged