Add/menus
yamada-ui/yamada-components pull request #265
Opened 2024-06-26 14:41 UTC by illionillion

Closes #166 

## Description

## Current behavior (updates)

## New behavior

## Is this a breaking change (Yes/No):

## Additional Information

2024-06-26 14:46 UTC, cidkumagai requested changes

2024-06-26 14:46 UTC, cidkumagai commented on contents/overlay/menus/menu-with-icon/metadata.json
> +    "description": ""
Please write English Description.

2024-06-26 14:46 UTC, cidkumagai commented on contents/overlay/menus/menu-with-icon/metadata.json
> +    "description": ""
Please write Japanese title and description.

2024-06-26 14:46 UTC, cidkumagai commented on contents/overlay/menus/simple-menu/metadata.json
> +    "description": ""
Please write English Description.

2024-06-26 14:46 UTC, cidkumagai commented on contents/overlay/menus/simple-menu/metadata.json
> +    "description": ""
Please write Japanese title and description.

2024-06-26 14:46 UTC, cidkumagai commented on contents/overlay/menus/simple-with-descriptions/metadata.json
> +    "description": ""
Please write English description.

2024-06-27 13:15 UTC, cidkumagai requested changes

2024-06-27 13:15 UTC, cidkumagai commented on contents/overlay/menus/simple-with-descriptions/metadata.json
> +    "title": "Simple With Descriptions",
please write Japanese.

2024-06-29 03:44 UTC, cidkumagai approved these changes
LGTM!

2024-06-29 14:22 UTC, hirotomoyamada approved these changes

2024-06-29 14:22 UTC, merged