feat: add mailbox
yamada-ui/yamada-components pull request #342
Opened 2024-07-05 11:28 UTC by illionillion

Closes #279 

## Description

## Current behavior (updates)

## New behavior

## Is this a breaking change (Yes/No):

## Additional Information

2024-07-05 22:57 UTC, setodeve submitted a review, later dismissed

2024-07-06 00:09 UTC, taroj1205 requested changes
Thanks for the PR! I have made a few suggestions, please check.

The item is active even after pressing "Archive", and I think I should be able to set it to active when clicking on the row.
It seems like the context menu does not close when I click outside, causing to open multiple context menus.

![image](https://github.com/yamada-ui/yamada-components/assets/61367823/2bbb9316-1b21-4a0a-9679-246838ca710d)

2024-07-06 00:09 UTC, taroj1205 commented on contents/overlay/context-menus/mail-box/index.tsx
> +      </MenuList>
Maybe you could add icon to menu items?
```suggestion
      <MenuList>
        <MenuItem icon={<TrashIcon color="danger" />} onClick={handleDelete}>
          Delete
        </MenuItem>
        <MenuItem
          icon={
            isArchived ? (
              <ArchiveRestoreIcon color="success" />
            ) : (
              <ArchiveIcon color="danger" />
            )
          }
          onClick={handleArchive}
        >
          {isArchived ? "Remove Archive" : "Archive"}
        </MenuItem>
      </MenuList>
```

2024-07-06 00:44 UTC, illionillion commented on contents/overlay/context-menus/mail-box/index.tsx
> +      </MenuList>
I accept you suggestion.

2024-07-06 00:51 UTC, illionillion commented on contents/overlay/context-menus/mail-box/index.tsx
> +}
Split into `mail-item.tsx`

2024-07-06 00:56 UTC, illionillion commented on contents/overlay/context-menus/mail-box/index.tsx
> +        bgColor={id === currentId ? "primary" : undefined}
How about this?

![image](https://github.com/yamada-ui/yamada-components/assets/60034520/01c97703-9d9a-484c-b8d3-ea14605b02dc)

![image](https://github.com/yamada-ui/yamada-components/assets/60034520/ef25ec46-9092-45fe-91c3-57bf5c04d234)

2024-07-06 04:20 UTC, taroj1205 approved these changes
Thanks!

2024-07-06 04:26 UTC, hirotomoyamada approved these changes

2024-07-06 04:27 UTC, merged