Refactor `Headers` components
yamada-ui/yamada-components pull request #486
Opened 2024-09-06 01:13 UTC by illionillion

Closes #459  

## Description

![image](https://github.com/user-attachments/assets/16e8c0e6-1304-439c-a84b-97b4d3816a1f)
![image](https://github.com/user-attachments/assets/5133e851-9e95-4f0e-bf38-759d8ba99632)
![image](https://github.com/user-attachments/assets/9a7e93ba-f7fc-406f-b021-a5f578a8424b)
![image](https://github.com/user-attachments/assets/0cccd89d-3089-4e67-b7c6-858285da43e3)

## Current behavior (updates)

## New behavior

## Is this a breaking change (Yes/No):

## Additional Information

2024-09-06 01:19 UTC, illionillion commented on contents/layouts/headers/with-tabs/index.tsx
> +                }}
I couldn't specify a style for the group-label of menu-item, so I'm specifying it directly,
 I'll fix it later.

2024-09-06 01:19 UTC, illionillion commented on contents/layouts/headers/with-tabs/index.tsx
> +                }}
https://github.com/yamada-ui/yamada-ui/blob/e7c8bd5020102c240f6b1dbc2855e34049c5f62f/packages/components/menu/src/menu-group.tsx#L30

2024-09-06 01:19 UTC, illionillion commented on contents/layouts/headers/with-tabs/index.tsx
> +                }}
Same here

2024-09-06 02:03 UTC, illionillion commented on contents/layouts/headers/with-tabs/index.tsx
> +                }}
A custom theme solved the problem.

2024-09-07 14:05 UTC, Haru-0001 commented on contents/layouts/headers/with-tabs/index.tsx
The `orientation=“vertical”` on line 138 is not necessary because tabs are not vertical.
https://yamada-ui.com/ja/components/disclosure/tabs/accessibility

2024-09-07 14:26 UTC, Haru-0001 requested changes
I think the style should be changed when the `Simple-Header` `links` is in hover state.

2024-09-07 14:33 UTC, Haru-0001 requested changes
I think the style of the `Tab` in `With-Tabs` needs to be changed when it is in a hover state.

2024-09-08 04:18 UTC, illionillion commented on contents/layouts/headers/with-tabs/index.tsx
fixed [89a9992](https://github.com/yamada-ui/yamada-components/pull/486/commits/89a99928645be26122f733bed69851b02c93fa22)

2024-09-08 04:40 UTC, illionillion commented
@Haru-0001 I fixed.
Please review again.

2024-09-08 08:42 UTC, Haru-0001 approved these changes
LGTM

2024-09-08 09:29 UTC, hirotomoyamada approved these changes

2024-09-08 09:29 UTC, merged