Fix pagination alignment
yamada-ui/yamada-components pull request #511
Opened 2024-09-30 15:31 UTC by Ncode-93

## UPDATE: Fix Pagination Alignment
This PR addresses the issue of pagination layout misalignment between 1-digit, 2-digit, and 3-digit page numbers, which was causing inconsistent spacing in the pagination component. The changes ensure that page numbers remain consistently aligned regardless of the number of digits displayed (e.g., page 1, page 10, page 100).

## Current behavior (updates):
--> Adjusted the pagination component's styling to ensure that page numbers of varying digit lengths (1-digit, 2-digit, 3-digit) are consistently aligned.
--> Introduced flexible padding and margin adjustments to handle cases where digit lengths change as the user navigates through different pages.
--> Reviewed and tested on various screen sizes to ensure the layout remains responsive.

## New behavior
Consistent pagination with no breaks for 1,2 or 3 digit numbers.

## Is this a breaking change (Yes/No): NO

2024-09-30 16:04 UTC, Ncode-93 commented
@illionillion Have a look

2024-10-01 01:46 UTC, illionillion requested changes
@Ncode-93 
Thank for PR!!

Correction please.

2024-10-01 01:46 UTC, illionillion commented on .gitignore
> +package-lock.json
This is not necessary.
lock file is not included in the diff if the library is not added.

2024-10-01 01:46 UTC, illionillion commented on contents/navigation/paginations/right-justified-with-page-position/index.tsx
Do not use the `span` tag directly.

```tsx
import { Text, Pagination, Flex, Box, ui } from "@yamada-ui/react"
import { useState, type FC } from "react"

const RightJustifiedWithPagePosition: FC = () => {
  const [page, onChange] = useState<number>(1)

  return (
    <Box w="full">
      <Flex justifyContent={{ base: "end", sm: "center" }}>
        <Pagination
          page={page}
          onChange={onChange}
          total={10}
          w="md"
          size={{ base: "md", sm: "sm", xs: "xs" }}
          variant="ghost"
        />
      </Flex>
      <Text
        fontSize="sm"
        color={["gray.700", "gray.200"]}
        textAlign="right"
        m="md"
      >
        Showing{" "}
        <ui.span
          display="inline-block"
          minWidth="20px"
          textAlign="center"
        >
          {page * 10 - 9}
        </ui.span>
        -
        <ui.span
          display="inline-block"
          minWidth="30px"
          textAlign="center"
        >
          {page * 10}
        </ui.span>{" "}
        of 100
      </Text>
    </Box>
  )
}

export default RightJustifiedWithPagePosition
```

2024-10-01 01:46 UTC, illionillion commented on contents/navigation/paginations/simple-button/index.tsx
Again, do not use `span` tags directly.

2024-10-01 02:11 UTC, illionillion commented on contents/navigation/paginations/simple-button/index.tsx
add `justifyContent="center"` in `Pagenation`

2024-10-02 10:52 UTC, Ncode-93 commented on contents/navigation/paginations/simple-button/index.tsx
```
<Pagination
        page={page}
        onChange={onChange}
        total={10}
        justifyContent={center}
        innerProps={{ display: "none" }}
        controlPrevProps={{
          children: (
            <Button variant="ghost" size="sm">
              Prev
            </Button>
          ),
        }}
        controlNextProps={{
          children: (
            <Button variant="ghost" size="sm">
              Next
            </Button>
          ),
        }}
      />
```
Thanks for pointing out. I think this is the pagination you are talking about.

2024-10-03 03:31 UTC, illionillion commented on contents/navigation/paginations/simple-button/index.tsx
```tsx
<Pagination
        page={page}
        onChange={onChange}
        total={10}
        justifyContent="center"
        innerProps={{ display: "none" }}
        controlPrevProps={{
          children: (
            <Button variant="ghost" size="sm">
              Prev
            </Button>
          ),
        }}
        controlNextProps={{
          children: (
            <Button variant="ghost" size="sm">
              Next
            </Button>
          ),
        }}
      />
```

2024-10-07 15:46 UTC, Ncode-93 commented
Hey @illionillion I have made the required changes. Have a look.

2024-10-08 04:00 UTC, illionillion approved these changes
LGTM!

2024-10-08 13:00 UTC, hirotomoyamada approved these changes

2024-10-08 13:01 UTC, merged

2024-10-12 10:01 UTC, illionillion commented
Closes #506